sudo: required
language: generic

services:
  - docker

env:
  - DOCKER_IMAGE_NAME=dstacademy/server

before_script: cd build
script:
  - docker build -t $DOCKER_IMAGE_NAME .

notifications:
  slack: dst-academy:$TRAVIS_CI_TOKEN
