sudo: required
language: generic

services:
  - docker

env:
  - DOCKER_IMAGE_NAME=dstacademy/server

before_install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

before_script: cd build
script:
  - docker build -t $DOCKER_IMAGE_NAME .
